/**:
  ros__parameters:
    # Storage parameters:
    # map_path is concatened with pose_graph_file_name to create the pose graph file. 
    # map_path is used to store the map and also to display the map in case that display_from_own_storage is true. 
    map_path: /home/colcon_ws/src/cslam_visualization/map
    pose_graph_file_name: pose_graph.json
    is_robot: false
    max_nb_robots: 2
    enable_own_storage: true